package dev.naominet.empurple.utils

import com.alibaba.fastjson2.JSONArray
import com.alibaba.fastjson2.JSONObject
import dev.naominet.empurple.maimai.dto.UserRatingData
import java.awt.Color
import java.awt.Graphics2D
import java.io.File
import javax.imageio.ImageIO

object Best50ImageRenderer {
    private const val maxB35 = 35
    private const val maxB15 = 15

    fun render(cacheJson: JSONObject, outputFile: File, qrContent: String? = null) {
        MusicDataProvider.load()
        val userRating = cacheJson.getJSONObject("userRating") ?: JSONObject()
        val ratingList = parse(userRating.getJSONArray("ratingList")).take(maxB35)
        val newRatingList = parse(userRating.getJSONArray("newRatingList")).take(maxB15)
        val b35 = ratingList.sumOf(::computeRa)
        val b15 = newRatingList.sumOf(::computeRa)

        val backgroundStream = Best50ImageRenderer::class.java.getResourceAsStream("/b50/base.png")
            ?: error("Missing B50 background resource")
        val background = backgroundStream.use(ImageIO::read)
        val graphics = background.createGraphics()
        DesignSystem.applyHints(graphics)

        ResourceHelper.iconImage(cacheJson.getString("iconId") ?: "0")
            ?.let { graphics.drawImage(it, 115, 110, null) }

        graphics.color = Color(61, 61, 61)
        graphics.font = DesignSystem.miSansBold(48)
        graphics.drawString(cacheJson.getString("userName") ?: "Unknown", 260, 165)
        graphics.font = DesignSystem.miSansRegular(24)
        graphics.drawString("B35:$b35 + B15:$b15 = ${b35 + b15}", 260, 200)
        graphics.drawString("Rating: ${cacheJson.getIntValue("playerRating")}", 260, 225)
        graphics.drawString("Generated by Empurple. UI designed by chuxuehaocai.", 70, 1740)

        (ratingList + newRatingList).forEachIndexed { index, record ->
            val row = index / 5
            val x = 65 + 320 * (index % 5)
            val y = if (row < 7) 350 + 120 * row else 1250 + 120 * (row - 7)
            ImageBuilder.drawRatingCard(graphics, record, x, y)
        }

        qrContent?.let { drawQrCode(graphics, background.width, background.height, it) }
        graphics.dispose()
        outputFile.parentFile?.mkdirs()
        ImageIO.write(background, "png", outputFile)
    }

    private fun drawQrCode(graphics: Graphics2D, width: Int, height: Int, content: String) {
        val size = 128
        val padding = 9
        val x = width - size - padding - 64
        val y = height - size - padding - 32

        graphics.drawImage(QrCodeRenderer.render(content, size), x, y, null)
    }

    private fun parse(array: JSONArray?): List<UserRatingData> {
        if (array == null) return emptyList()
        return (0 until array.size).map { index ->
            val item = array.getJSONObject(index)
            UserRatingData(
                musicName = MusicDataProvider.getTitle(item.getIntValue("musicId")),
                level = item.getIntValue("level"),
                achievement = item.getIntValue("achievement"),
                musicId = item.getIntValue("musicId"),
                comboStatus = item.getIntValue("comboStatus"),
                syncStatus = item.getIntValue("syncStatus")
            )
        }
    }

    private fun computeRa(data: UserRatingData): Int = RatingCalculator.computeRa(
        MusicDataProvider.getDs(data.musicId, data.level),
        data.achievement / 10000.0
    )
}
