package dev.naominet.empurple.maimai.dto

import com.alibaba.fastjson2.annotation.JSONField

data class UserAllData(
    @JSONField(name = "userId") val userId: Long = 0,
    @JSONField(name = "userData") val userData: UserAllDataBean = UserAllDataBean(),
    @JSONField(name = "banState") val banState: Int = 0
)

data class UserAllDataBean(
    @JSONField(name = "accessCode") val accessCode: String? = null,
    @JSONField(name = "userName") val userName: String = "",
    @JSONField(name = "friendCode") val friendCode: Long? = null,
    @JSONField(name = "isNetMember") val isNetMember: Int = 0,
    @JSONField(name = "point") val point: Long = 0,
    @JSONField(name = "totalPoint") val totalPoint: Long = 0,
    @JSONField(name = "playerRating") val playerRating: Int = 0,
    @JSONField(name = "playerOldRating") val playerOldRating: Int = 0,
    @JSONField(name = "playerNewRating") val playerNewRating: Int = 0,
    @JSONField(name = "highestRating") val highestRating: Int = 0,
    @JSONField(name = "gradeRating") val gradeRating: Int = 0,
    @JSONField(name = "musicRating") val musicRating: Int = 0,
    @JSONField(name = "gradeRank") val gradeRank: Int = 0,
    @JSONField(name = "courseRank") val courseRank: Int = 0,
    @JSONField(name = "classRank") val classRank: Int = 0,
    @JSONField(name = "nameplateId") val nameplateId: Int = 0,
    @JSONField(name = "frameId") val frameId: Int = 0,
    @JSONField(name = "iconId") val iconId: Int = 0,
    @JSONField(name = "trophyId") val trophyId: Int = 0,
    @JSONField(name = "plateId") val plateId: Int = 0,
    @JSONField(name = "titleId") val titleId: Int = 0,
    @JSONField(name = "partnerId") val partnerId: Int = 0,
    @JSONField(name = "charaSlot") val charaSlot: List<Int> = emptyList(),
    @JSONField(name = "charaLockSlot") val charaLockSlot: List<Int> = emptyList(),
    @JSONField(name = "contentBit") val contentBit: Long = 0,
    @JSONField(name = "selectMapId") val selectMapId: Int = 0,
    @JSONField(name = "playCount") val playCount: Long = 0,
    @JSONField(name = "currentPlayCount") val currentPlayCount: Long = 0,
    @JSONField(name = "playVsCount") val playVsCount: Long = 0,
    @JSONField(name = "playSyncCount") val playSyncCount: Long = 0,
    @JSONField(name = "winCount") val winCount: Long = 0,
    @JSONField(name = "helpCount") val helpCount: Long = 0,
    @JSONField(name = "comboCount") val comboCount: Long = 0,
    @JSONField(name = "totalDeluxscore") val totalDeluxscore: Long = 0,
    @JSONField(name = "totalBasicDeluxscore") val totalBasicDeluxscore: Long = 0,
    @JSONField(name = "totalAdvancedDeluxscore") val totalAdvancedDeluxscore: Long = 0,
    @JSONField(name = "totalExpertDeluxscore") val totalExpertDeluxscore: Long = 0,
    @JSONField(name = "totalMasterDeluxscore") val totalMasterDeluxscore: Long = 0,
    @JSONField(name = "totalReMasterDeluxscore") val totalReMasterDeluxscore: Long = 0,
    @JSONField(name = "totalSync") val totalSync: Long = 0,
    @JSONField(name = "totalBasicSync") val totalBasicSync: Long = 0,
    @JSONField(name = "totalAdvancedSync") val totalAdvancedSync: Long = 0,
    @JSONField(name = "totalExpertSync") val totalExpertSync: Long = 0,
    @JSONField(name = "totalMasterSync") val totalMasterSync: Long = 0,
    @JSONField(name = "totalReMasterSync") val totalReMasterSync: Long = 0,
    @JSONField(name = "totalAchievement") val totalAchievement: Long = 0,
    @JSONField(name = "totalBasicAchievement") val totalBasicAchievement: Long = 0,
    @JSONField(name = "totalAdvancedAchievement") val totalAdvancedAchievement: Long = 0,
    @JSONField(name = "totalExpertAchievement") val totalExpertAchievement: Long = 0,
    @JSONField(name = "totalMasterAchievement") val totalMasterAchievement: Long = 0,
    @JSONField(name = "totalReMasterAchievement") val totalReMasterAchievement: Long = 0,
    @JSONField(name = "eventWatchedDate") val eventWatchedDate: String = "",
    @JSONField(name = "lastGameId") val lastGameId: String? = null,
    @JSONField(name = "lastRomVersion") val lastRomVersion: String = "",
    @JSONField(name = "lastDataVersion") val lastDataVersion: String = "",
    @JSONField(name = "lastLoginDate") val lastLoginDate: String = "",
    @JSONField(name = "lastPlayDate") val lastPlayDate: String = "",
    @JSONField(name = "lastPairLoginDate") val lastPairLoginDate: String = "",
    @JSONField(name = "lastTrialPlayDate") val lastTrialPlayDate: String = "",
    @JSONField(name = "lastPlayCredit") val lastPlayCredit: Int = 0,
    @JSONField(name = "lastPlayMode") val lastPlayMode: Int = 0,
    @JSONField(name = "lastPlaceId") val lastPlaceId: Int = 0,
    @JSONField(name = "lastPlaceName") val lastPlaceName: String? = null,
    @JSONField(name = "lastAllNetId") val lastAllNetId: Int = 0,
    @JSONField(name = "lastRegionId") val lastRegionId: Int = 0,
    @JSONField(name = "lastRegionName") val lastRegionName: String = "",
    @JSONField(name = "lastClientId") val lastClientId: String? = null,
    @JSONField(name = "lastCountryCode") val lastCountryCode: String = "",
    @JSONField(name = "lastSelectEMoney") val lastSelectEMoney: Int = 0,
    @JSONField(name = "lastSelectTicket") val lastSelectTicket: Int = 0,
    @JSONField(name = "lastSelectCourse") val lastSelectCourse: Int = 0,
    @JSONField(name = "lastCountCourse") val lastCountCourse: Int = 0,
    @JSONField(name = "firstGameId") val firstGameId: String = "",
    @JSONField(name = "firstRomVersion") val firstRomVersion: String = "",
    @JSONField(name = "firstDataVersion") val firstDataVersion: String = "",
    @JSONField(name = "firstPlayDate") val firstPlayDate: String = "",
    @JSONField(name = "compatibleCmVersion") val compatibleCmVersion: String = "",
    @JSONField(name = "totalAwake") val totalAwake: Int = 0,
    @JSONField(name = "dailyBonusDate") val dailyBonusDate: String = "",
    @JSONField(name = "dailyCourseBonusDate") val dailyCourseBonusDate: String = "",
    @JSONField(name = "mapStock") val mapStock: Int = 0,
    @JSONField(name = "renameCredit") val renameCredit: Int = 0,
    @JSONField(name = "friendRegistSkip") val friendRegistSkip: Int = 0,
    @JSONField(name = "cmLastEmoneyCredit") val cmLastEmoneyCredit: Int = 0,
    @JSONField(name = "cmLastEmoneyBrand") val cmLastEmoneyBrand: Int = 0,
    @JSONField(name = "dateTime") val dateTime: Long? = null
)
